### ISSUE TITLE
Feature Request: Automatic tag reordering

### ISSUE THREAD

**Issue by Neo-Oli** [mdom/squaretag#2]
Hi

I really like this software and its rationale, and I have been using it for several years without problems and have tagged many files with it. Sometimes however I will manually mutate the tags using `mv` or `rename`. It would be great if there was a function in squaretag that would automatically reorder all tags alphabetically. 

Currently this is only done when adding or removing a tag. So `squaretag add foobar file*; squaretag remove foobar file*` works as a workaround, but it would be nice if there was a single command to do it. Something like `squaretag sort` perhaps.

**Comment by mdom** [comment]
Thanks for the kind words and the feature request. It was quite a ride to add a feature to seven year old code.  I did not recognize anything :)

**Comment by Neo-Oli** [comment]
@mdom Awesome thanks for implementing this this quickly.
